version: "3.8"
services:

  php-ws:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-${APP_NAME}-mexico
    container_name: php-${APP_NAME}-mexico
    restart: unless-stopped
    tty: true
    working_dir: ${WORKING_DIR}
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - ./src:/var/www/
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  nginx-ws:
    image: nginx
    hostname: web-${APP_NAME}
    container_name: web-${APP_NAME}-mexico
    restart: unless-stopped
    ports:
      - ${PORT_NGNIX}:80
    volumes:
      - ./src:/var/www/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-ws
    networks:
      - app-network
  
  mysql-ws:
    image: mysql:8
    container_name: mysql-${APP_NAME}
    hostname: mysql-${APP_NAME}
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    expose:
      - '3306'
    volumes:
      # - ./config/mysql/schemas:/var/lib/mysql
       - volume-app:/var/lib/mysql
    networks:
      - app-network    

networks:
  app-network:
    name: ${NETWORK_EXTERNAL_NAME}-network
    external: true
volumes:
  schemas: {}
  volume-app:
    name: ${APP_NAME}-volume